# Generated by Django 4.2.2 on 2023-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoModels",
            fields=[
                ("taskId", models.AutoField(primary_key=True, serialize=False)),
                ("taskTitle", models.CharField(max_length=100)),
                ("taskDescription", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
